version: '3'
services:
  postgresql:
    image: "docker.io/bitnami/postgresql:11"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
  keycloak:
    container_name: keycloak-email
    image: summit/keycloak-otp-email:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      TZ: "Europe/Berlin"
    ports:
      - 9990:9990
      - 8080:8080
    depends_on:
      - postgresql
  mail:
    container_name: mail
    image: djfarrelly/maildev
    ports:
      - 9080:80
volumes:
  postgresql_data:
    driver: local