version: '3'
services:
  keycloak:
    container_name: keycloak
    image: summit/keycloak-otp-email:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9990:9990
      - 8080:8080
  mail:
    container_name: mail
    image: djfarrelly/maildev
    ports:
      - 9080:80